server:
  port: 8083

spring:
  application:
    name: client-performance-svc

logging:
  level:
    root: INFO
    com.edjobim.performance: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
