server:
  port: 8084

spring:
  application:
    name: aims-config-central

logging:
  level:
    root: INFO
    com.edjobim.aims: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
